namespace SheroShayari.API.Models;

/// <summary>
/// Represents a Shayari (poetic verse) with metadata.
/// </summary>
public class Shayari
{
    /// <summary>
    /// Unique identifier for the Shayari.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// The main poetic content (in Hindi, Urdu, or English).
    /// </summary>
    public required string Content { get; set; }

    /// <summary>
    /// The poet or author of the Shayari. For AI-generated ones, can be "AI Generator".
    /// </summary>
    public required string Poet { get; set; }

    /// <summary>
    /// Language of the Shayari (e.g., "Hindi", "Urdu", "English").
    /// </summary>
    public required string Language { get; set; }

    /// <summary>
    /// Category or theme of the Shayari (e.g., "Love", "Philosophy", "Nature").
    /// </summary>
    public required string Category { get; set; }

    /// <summary>
    /// Optional meaning or translation of the Shayari in English.
    /// </summary>
    public string? Meaning { get; set; }

    /// <summary>
    /// Indicates whether the Shayari was generated by AI or sourced from the database.
    /// </summary>
    public bool IsAiGenerated { get; set; }

    /// <summary>
    /// Indicates if this Shayari is publicly visible (not restricted to owner).
    /// </summary>
    public bool IsPublic { get; set; } = false;

    /// <summary>
    /// Timestamp when the Shayari was created or added to the database.
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Foreign key to the user who created/owns this Shayari. Null for pre-seeded public Shayaris.
    /// </summary>
    public string? UserId { get; set; }

    /// <summary>
    /// Navigation property to the user who created this Shayari.
    /// </summary>
    public ApplicationUser? User { get; set; }
}
